### ISSUE TITLE
Does not work on my IC-9700

### ISSUE THREAD

**Issue by g0lgs** [Kurgan-/icom-set-time#1]
Whilst this works ok on my My IC-7300 it does not set the time on my IC-9700 when I change the address to 0xa2 and the correct Serial port

**Comment by g0lgs** [comment]
Seems that this is because the CI-V commands are different for the 9700 to the 7300

![image](https://github.com/Kurgan-/icom-set-time/assets/64634584/9c959c4e-1b6a-41c5-95c4-33732d1c65ef)

**Comment by Kurgan-** [comment]
I see. I actually have a 9700 too, but I never tested it on the 9700 because while my 9700 has a faulty RTC battery (as ALL icom radios have because of a poor design choice) the 9700 has, like the 705, an NTP client. So for the 9700 I have set it up to connect to my network and set its clock using NTP at power on, which is something the 7300 cannot do.
If you can, I suggest that you use NTP on the 9700, which will also give you precise time, and not the one minute error range you get with the 7300 and my script.

**Comment by g0lgs** [comment]
My 9700 when in the shack does do NTP, but a few days each year I take it /P (in car) for contests and I then do not have Ethernet so I was looking to set something up. Having found the above commands I have now made a couple of changes to make a version work for the 9700.

Thanks.
